### ISSUE TITLE
outlets in MSP template

### ISSUE THREAD

**Issue by scblakely** [grrrwaaa/maxcpp#12]
I have written an external using maxcpp - the dsp part works fine, and I am getting the analysis I want from the audio stream.

However, I cannot seem to create outlets for my data (int, a list of floats, a list of int, a string). I can add an outlet, but it just shows up as a signal outlet in patcher.

Am I missing something?

Thanks

Simon

**Comment by scblakely** [comment]
And I added a m_outlets pointer and created the outlets I needed using that, and I now have the outlets working. On to the next issue, lists ...

Learning lots, though.

Simon

**Comment by grrrwaaa** [comment]
Yeah, the maxcpp files are just designed to solve the most common cases, not a pervasive wrapper of the SDK. Sometimes you have to dig down to the SDK level to get what you need. :-)
