### ISSUE TITLE
VS project files not working?

### ISSUE THREAD

**Issue by johnty** [grrrwaaa/maxcpp#4]
It looks like the Visual Studio solutions are not loading properly? Specifically, the max folder seems to be missing the project file, and the msp project file doesn't open by itself, so the entire solution doesn't load either project. Can anyone confirm this, or did I do something silly? :) Thanks!

**Comment by roskit** [comment]
@growlerpig any luck?

**Comment by growlerpig** [comment]
@roskit i'm afraid not, my files were incompatible with VS2010 so i gave up in the end...

**Comment by grrrwaaa** [comment]
I also had no luck merging in the pull request for the VS project files, too many merge conflicts and I don't know which one is right.
